version: "3"

services:

  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=stickerocr
    ports:
      - "5432:5432"
    volumes:
    - ./data:/var/lib/postgresql/data:rw
    - ./postgres.conf:/etc/postgresql/postgresql.conf:roz

  bot:
    build:
      context: ./bot
    image: ghcr.io/graynk/sticker_ocr_bot:latest
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DB_URL=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./bot/model:/root/.EasyOCR/model
    runtime: nvidia

  editor:
    build:
      context: ./editor
    image: ghcr.io/graynk/sticker_ocr_editor:latest
    depends_on:
      - db
      - bot
    restart: unless-stopped
    environment:
      - DB_URL=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - USER_HASH=7ed0e3fc7bf3fe79d35109ec42cfe90872a16eccb65b41069ec60a7af3ab9148
    ports:
      - "8085:80"