name: Publish Docker image
on:
    release:
        types: [published]
jobs:
    docker:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to Github Actions
            uses: docker/login-action@v2
            with:
                username: ${{ github.actor }}
                password: ${{ secrets.CR_PAT }}
                registry: ghcr.io
          -
            name: Build and push bot
            uses: docker/build-push-action@v4
            with:
                context: {{defaultContext}}:bot
                pull: true
                push: true
                tags: ghcr.io/graynk/sticker_ocr_bot:latest
                platforms: linux/amd64
          -
            name: Build and push editor
            uses: docker/build-push-action@v4
            with:
                context: {{defaultContext}}:editor
                pull: true
                push: true
                tags: ghcr.io/graynk/sticker_ocr_editor:latest
                platforms: linux/amd64       
